//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerQualityManageService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Report {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Report() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerQualityManageService.Resources.Report", typeof(Report).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatkowe wykresy.
        /// </summary>
        internal static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgodność z normą.
        /// </summary>
        internal static string Compliance {
            get {
                return ResourceManager.GetString("Compliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treść.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przy użyciu : PowerQualityManger.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygenerowano: .
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obejmuje zakres:.
        /// </summary>
        internal static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od:  .
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport Wygenerowano dla stacji: .
        /// </summary>
        internal static string GeneratedFor {
            get {
                return ResourceManager.GetString("GeneratedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykresy pomocnicze.
        /// </summary>
        internal static string Graphs {
            get {
                return ResourceManager.GetString("Graphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak danych.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr normy.
        /// </summary>
        internal static string Norm {
            get {
                return ResourceManager.GetString("Norm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1)   Wartośc średnia częstotliwości mierzonej przez 10 sekund w miejsach przyłączenia powinna być zawarta w przedziale:.
        /// </summary>
        internal static string Norm1 {
            get {
                return ResourceManager.GetString("Norm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a) 50 Hz ±1 % (od 49,5 Hz do 50,5 Hz) przez 99,5 % tygodnia.
        /// </summary>
        internal static string Norm1a {
            get {
                return ResourceManager.GetString("Norm1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b) 50 Hz +4 % / –6 % (od 47 Hz do 52 Hz) przez 100 % tygodnia.
        /// </summary>
        internal static string Norm1b {
            get {
                return ResourceManager.GetString("Norm1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2)   W każdym tygodniu 95 % ze zbioru 10-minutowych średnich wartości skutecznych napięcia zasilającego powinno mieścić sie w przedziale odchyleń +- 10% napięcia znamionowego.
        /// </summary>
        internal static string Norm2 {
            get {
                return ResourceManager.GetString("Norm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3)   Przez 95 % czasu każdego tygodnia wskaźnik długookresowego migotania świata Plt spowodowanego wahaniami napięcia zasilającego nie powinien być większy od 1.
        /// </summary>
        internal static string Norm3 {
            get {
                return ResourceManager.GetString("Norm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4)   W ciągu każdego tygodnia 95 % ze zbioru 10-minutowych średnich wartości skutecznych:.
        /// </summary>
        internal static string Norm4 {
            get {
                return ResourceManager.GetString("Norm4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a) Składowej symetrycznej kolejności przeciwnej napięcia zasilającego powinno mieścić się w przedziale od 0 % do 2 % wartości składowej kolejności zgodnej.
        /// </summary>
        internal static string Norm4a {
            get {
                return ResourceManager.GetString("Norm4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b) Dla każdej harmonicznej napięcia zasilającego powinno być mniejsze lub równe wartościom określonym w poniższej tabeli:.
        /// </summary>
        internal static string Norm4b {
            get {
                return ResourceManager.GetString("Norm4b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5)   Współczynnik odkształcenia wyższymi harmonicznymi napięcia zasilającego THD uwzględniający wyższe harmoniczne do rzędu 40, powinien być mniejszy lub równy 8 %.
        /// </summary>
        internal static string Norm5 {
            get {
                return ResourceManager.GetString("Norm5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6)   Warunkiem utrzymania parametrów napięcia zasilającego w granicach określonych w pkt 1—5 jest pobieranie przez odbiorcę mocy nie większej od mocy umownej, przy współczynniku tg fi nie większym niż 0,4.
        /// </summary>
        internal static string Norm6 {
            get {
                return ResourceManager.GetString("Norm6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normy.
        /// </summary>
        internal static string Norms {
            get {
                return ResourceManager.GetString("Norms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poprawność parametrów energii elektrycznej jest opracowana na podstawie rozporządzenia ministra gospodarki z dnia 4 maja 2077r. w sprawie szczegółowych warunków funkcjonowania systemu elektroenergetycznego. Dziennik Ustaw Nr 93 Poz. 623..
        /// </summary>
        internal static string Ordinance {
            get {
                return ResourceManager.GetString("Ordinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powód.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynik.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niniejsze opracowanie zostało opracowane dzięki aplikacji PowerQualityManager stworzonej w ramach pracy magisterskiej autorstwa Szymon Lis. .
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport z analizy jakości energii elektrycznej.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do: .
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
